### ISSUE TITLE
Insecure download of amalgamation

### ISSUE THREAD

**Issue by dionyziz** [leapcode/pysqlcipher#13]
The following is a non-HTTPS download of unsigned code that is downloaded and executed on the user's machine. This is trivial to tamper with and insert a virus into for any attacker with very basic techniques:

https://github.com/leapcode/pysqlcipher/blob/e42f5a80391f7a4cb3b1305990ab3842ac2bea53/setup.py#L125

This puts all users of pysqlcipher at risk. As pysqlcipher is a security-related library, this issue is critical. In particular, because it's used in our project, OpenBazaar, a project related to bitcoin, it is a vector for bitcoin-stealing malware.

This should be replaced with either of these options:
(1) An HTTPS-based download
(2) An insecure download followed by checksum verification, where the checksum is hard-coded in the installer

**Comment by yurivict** [comment]
Hi @kalikaneko ,
I think the original conflict has been resolved in libsqlcipher. Do you know when you are able to fix and fix this bug? I think OpenBazaar folks depend on it for their upcoming release, and still have to use amalgamation.

**Comment by kalikaneko** [comment]
hi @yurivict. If you're talking about the non-ssl download of amalgamation, this was fixed in 2.6.4 release of pysqlcipher now available by default in pypi.
If you're talking about compiling against the the libsqlcipher dependency, that's indeed possible, see the README.

I think it's not a problem that the extension in pysqclipher is called _sqlite.so, since it doesn't collide with pysqite namespace.

Closing this issue.
